[package]
name = "exlib"
edition = "2024"
license.workspace = true
description.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
zintl = { path = "../../core/zintl" }
