[package]
name = "ztloop"
edition = "2024"
license.workspace = true
description.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
futures = "0.3"

[[example]]
name = "loop"
